name:                bfhs
version:             0.1.0.0
github:              "mesabloo/bfhs"
author:              "Mesabloo"
copyright:           "2019 Mesabloo"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mesabloo/bfhs#readme>

dependencies:
- base >= 4.7 && < 5
- array
- mtl
- MissingH
- ansi-terminal
- lens
- bytestring

library:
  source-dirs: src
  ghc-options:
  - -O6
  - -optc-O3
  - -fasm
  - -Wall
  cpp-options:
  - -DNDEBUG
  - -O4

executables:
  bfhs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O6
    - -optc-O3
    - -fasm
    - -Wall
    cpp-options:
    - -DNDEBUG
    - -O4
    dependencies:
    - bfhs
